### ISSUE TITLE
Permission issue when I install the dashboard

### ISSUE THREAD

**Issue by Kopry** [NMonst4/gravcms-docker#1]
Hi, I recently used your dockerfile image to build my container.
Thanks for the patch with the docker file it's work compared to the old image from benjick.

I also installed the admin panel, But now when I want to access to plugins tab in the admin panel I got a number of permission error.

I found a way to fix the problem
If I connect to the container and change permissions manually in the gpm/cache to stick with the group www-data, well it's works, no more error and I can load the plugins and theme tab

`docker exec -i -t grav /bin/bash
cd /var/www/html/cache/`

```
root@bd3b4c0668f0:/var/www/html/cache# ls -la
total 32
drwxrwxr-x  1 www-data www-data 4096 May  8 16:46 .
drwxrwxr-x  1 www-data www-data 4096 May  8 16:30 ..
-rw-rw-r--  1 www-data www-data    0 Apr 12 21:54 .gitkeep
drwxr-xr-x  1 www-data www-data 4096 May  8 16:47 compiled
drwxr-xr-x  1 www-data www-data 4096 May  8 16:52 doctrine
drwxr-xr-x  1 root root 4096 May  8 16:30 gpm <---------- Something wrong here
drwxr-xr-x  2 www-data www-data 4096 May  8 16:33 rememberme
drwxr-xr-x 61 www-data www-data 4096 May  8 16:53 twig
drwxr-xr-x  2 www-data www-data 4096 May  8 16:52 twigfeeds
```

So I just set the permission for the directory gpm.
`chown -R www-data:www-data gpm/`
And now I can reach my plugins and theme tabs.

When using the command 
`docker exec grav bin/gpm install chalk`
installed packages must probably take permission from user root, user www-data can't access to the installed package

**Comment by Kopry** [comment]
Maybe indicate in the readme file this line? 

`docker exec --user www-data mygrav bin/gpm install <something>`

**Comment by NMathar** [comment]
thnak you i added this to the readme
